### ISSUE TITLE
items show limit not working an angular 8

### ISSUE THREAD

**Issue by mrsants** [NileshPatel17/ng-multiselect-dropdown#323]
**Angular version**:
8.2.8

**ng-multiselect-dropdown version**:
"^0.3.4",

**Description of issue**:
I'm trying to limit the amount of items in the input text, but the itemsShowLimit property doesn't respond, I tested it with version 0.2.1 and apparently it worked

**Steps to reproduce**:
  angular 8.2.8
  node v10.24.1
```
example: https://stackblitz.com/edit/ng-multiselect-dropdown
```

**Comment by Philly-B** [comment]
Same problem for us. It seems that the syntax of ngFor in 

> multi-select.component.html

is not valid in terms of receiving the index. 

`
*ngFor="let item of selectedItems;trackBy: trackByFn;let k = index"
`

I think it should be `index as k;` instead. This statement seem to destroy the following [hidden] statement `[hidden]="k > _settings.itemsShowLimit-1"`.

Therefore the fix should be rather simple by changing `let k = index` to `index as k`, am I missing anything?

If I'm correct with my hypothesis, I can provide a pull request for this to save you some work (however it's just changing this one line).

P.S. By the way, the dropdown limit should also be affected with this problem since there is also a statement like `let i = index` in line `<li *ngFor="let item of _data | multiSelectFilter:filter; let i = index;" (click)="onItemClick($event,item)" class="multiselect-item-checkbox">`

**Comment by mrsants** [comment]
closed for no answer

**Comment by c4rnot** [comment]
Why is this closed?  I'm having the same problem!

**Comment by mrsants** [comment]
> Why is this closed? I'm having the same problem!

I'm reopening, but I find it difficult to answer

**Comment by c4rnot** [comment]
The fix is very simple.  You need some brackets:
[hidden]="k > (_settings.itemsShowLimit-1)"

**Comment by c4rnot** [comment]
Ive created a pull request with a fix..

https://github.com/NileshPatel17/ng-multiselect-dropdown/pull/325#issue-690007416

**Comment by ermarkar** [comment]
so any solution so far? even for me it is not showing Select All and UnSelect

**Comment by mrsants** [comment]
> Ive created a pull request with a fix..
> 
> https://github.com/NileshPatel17/ng-multiselect-dropdown/pull/325#issue-690007416

someone managed to validate your pull

**Comment by travisjwalter** [comment]
@NileshPatel17 Can we get an update on this?

**Comment by walldiv** [comment]
can we get an update on this?  @c4rnot  created a pull request with an answer 5 months ago....

**Comment by travisjwalter** [comment]
This is now working on v0.3.7
