### ISSUE TITLE
Clearing form dosent reflect in UI

### ISSUE THREAD

**Issue by bbdangar** [NileshPatel17/ng-multiselect-dropdown#40]
After submitting the form when trying to reset the form drop-down still shows the previously selected value in UI only. Once you click on drop-down it will get cleared.

So basically drop-down should not show previously selected values after resetting values.

I have faced this issue with FormGroup, haven't tried with ngModal.

**Comment by NileshPatel17** [comment]
Please share sample code using codesandbox or https://stackblitz.com

**Comment by Arun693** [comment]
+1. Form reset is not resetting the drop down.

**Comment by quiters89** [comment]
how to reset the dropdown after submit sir? the data is okay but the UI wont.

**Comment by arunkumarbrt** [comment]
Any Solution for this Issue

**Comment by gserg** [comment]
An example of reactive form w/multiselect and reset button https://stackblitz.com/edit/angular-ivy-zemxre
Steps to reproduce:
1. Select some value(s)
2. Click on 'Reset' button (value in model is updated, but this is not reflected in multiselect UI)
3. Click anywhere outside droprown (UI is updated)

**Comment by gserg** [comment]
Looks like this bug is related to the Angular's issue with `ControlValueAccessor` and `ChangeDetectionStrategy.OnPush` (https://github.com/angular/angular/issues/10816)

Possible solutions:
1. Use default change detection strategy instead of `OnPush`
2. Run change detection explicitly (https://github.com/angular/angular/issues/10816#issuecomment-307567836)

I've created pull request with second one.

**Comment by NileshPatel17** [comment]
@arunkumarbrt @gserg @bbdangar @quiters89  please verify with new release v0.3.5

**Comment by gserg** [comment]
> ... @gserg ... please verify with new release v0.3.5
Works for me after upgrade!
Thanks for approving MR!
